services:
  web:
    image: ticketing:1.0.0
    build: .
    command: ["python", "manage.py", "collectstatic"],["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
