# Generated by Django 3.2.5 on 2023-08-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categories',
            field=models.CharField(choices=[('To do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='To do', max_length=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(choices=[('Nanggroe Aceh Darussalam', 'Nad'), ('Sumatera Utara', 'Sumut'), ('Sumatera Selatan', 'Sumsel'), ('Sumatera Barat', 'Sumbar'), ('Bengkulu', 'Bengkulu'), ('Riau', 'Riau'), ('Kepulauan Riau', 'Kriau'), ('Jambi', 'Jambi'), ('Lampung', 'Lampung'), ('Bangka Belitung', 'Bangka'), ('Kalimantan Barat', 'Kalbar'), ('Kalimantan Timur', 'Kaltim'), ('Kalimantan Selatan', 'Kalsel'), ('Kalimantan Tengah', 'Kalteng'), ('Kalimantan Utara', 'Kalut'), ('Banten', 'Banten'), ('Jakarta', 'Jkt'), ('Jawa Barat', 'Jabar'), ('Jawa Tengah', 'Jateng'), ('Yogyakarta', 'Yogya'), ('Jawa Timur', 'Jatim'), ('Bali', 'Bali'), ('Nusa Tenggara Timur', 'Ntt'), ('Nusa Tenggara Barat', 'Ntb'), ('Gorontalo', 'Gorontalo'), ('Sulawesi Barat', 'Sulbar'), ('Sulawesi Tengah', 'Sulteng'), ('Sulawesi Utara', 'Sulut'), ('Sulawesi Tenggara', 'Sultengg'), ('Sulawesi Selatan', 'Sulsel'), ('Maluku Utara', 'Mlkut'), ('Maluku', 'Mlk'), ('Manokwari', 'Papuab'), ('Jayapura', 'Papua'), ('Nabire', 'Papuat'), ('Jayawijaya', 'Papuap'), ('Merauke', 'Papuas'), ('Sorong', 'Papuabd')], default='Jakarta', max_length=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='media',
            field=models.FileField(default=None, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('To do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], default='To do', max_length=25),
        ),
    ]
