# Generated by Django 3.2.5 on 2023-10-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0005_auto_20230822_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
