# Generated by Django 3.2.5 on 2023-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0006_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchase_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='purchase at'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='media',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
