# Generated by Django 3.2.5 on 2023-10-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0007_auto_20231017_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='media',
            new_name='media_nd',
        ),
        migrations.AddField(
            model_name='ticket',
            name='media_rd',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='media_st',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
